version: '3.7'
services:
  apache:
    build: .
    restart: always
    ulimits:
      nofile:
        soft: 10240
        hard: 10240
    volumes:
      - ./htdocs:/var/www/html
    logging:
      driver: 'json-file'
      options:
        max-file: '2'
        max-size: '2m'
    ports:
      - 80:80
      - 443:443